# Legacy App -> Moves to PHP 5.6 Container
server {
    listen 80;
    server_name app-legacy.test;
    root /var/www/html/app-legacy/public;
    index index.php index.html;

    location ~ \.php$ {
        fastcgi_pass php56:9000; # Points to the php56 container.
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

# Modern App -> Moves to PHP 7.0 Container
server {
    listen 80;
    server_name app-modern.test;
    root /var/www/html/app-modern/public;
    index index.php index.html;

    location ~ \.php$ {
        fastcgi_pass php70:9000; # Points to the php70 container.
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}